version: "3.9"

services:

  db:
    container_name: PostgresSQL
    restart: always
    build:
      dockerfile: docker/postgres/Dockerfile
      context: .
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PORTS_DB}

  web:
    container_name: Django_web_site
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PYTHONUNBUFFERED: 1
    restart: always
    volumes:
      - .:/IMDB-django
      - ./static:/static
      - ./media:/media
    depends_on:
      - db
    ports:
      - ${PORTS_WEB}

  nginx:
    container_name: Nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: docker/nginx
    links:
      - db
      - web
    ports:
      - "80:80"
    volumes:
      - .:/IMDB-django
      - ./static:/static

volumes:
  pgdata: